### ISSUE TITLE
prep_gtk.sh error (gtk 3.18.6)

### ISSUE THREAD

**Issue by ephja** [StefanSalewski/nim-gtk3#4]
Is this because I have a recent c2nim version? Which revision does it work with? Because there aren't any tags.
```
home/exe/src/nim-libs/nim-gtk3/gen/tmp_gtk/final.h(2712, 33) Error: ';' expected
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
../remdef.rb:8:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../remdef.rb:8:in `<main>'
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
../glib_fix_T.rb:7:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../glib_fix_T.rb:7:in `<main>'
../fix_new.rb:25:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../fix_new.rb:25:in `<main>'
../glib_fix_proc.rb:20:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../glib_fix_proc.rb:20:in `<main>'
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
../glib_fix_enum_prefix.rb:7:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../glib_fix_enum_prefix.rb:7:in `<main>'
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
../underscorefix.rb:8:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../underscorefix.rb:8:in `<main>'
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
../fix_template.rb:5:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../fix_template.rb:5:in `<main>'
../fix_object_of.rb:9:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../fix_object_of.rb:9:in `<main>'
../fix_reserved.rb:7:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../fix_reserved.rb:7:in `<main>'
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
csplit: cannot open ‘final.nim’ for reading: No such file or directory
mv: cannot stat ‘xx00’: No such file or directory
mv: cannot stat ‘xx01’: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(\n\s*)(proc set_)(\w+)(\*\([^}]*\) { <-- HERE [^}]*})/ at -e line 1.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
../mangler.rb:7:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../mangler.rb:7:in `<main>'
sed: can't read final.nim: No such file or directory
../mangler.rb:7:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../mangler.rb:7:in `<main>'
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
Can't open final.nim: No such file or directory.
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
sed: can't read final.nim: No such file or directory
../gen_proc_dep.rb:4:in `read': No such file or directory @ rb_sysopen - final.nim (Errno::ENOENT)
        from ../gen_proc_dep.rb:4:in `<main>'
cp: cannot stat ‘dep.txt’: No such file or directory
sed: can't read dep1.txt: No such file or directory
cat: dep1.txt: No such file or directory
cp: cannot stat ‘dep.txt’: No such file or directory
sed: can't read dep1.txt: No such file or directory
sed: can't read dep1.txt: No such file or directory
sed: can't read dep1.txt: No such file or directory
cat: dep1.txt: No such file or directory
sed: can't read dep.txt: No such file or directory
cat: dep.txt: No such file or directory
sed: can't read proc_dep_list: No such file or directory
sed: can't read proc_dep_list: No such file or directory
sed: can't read proc_dep_list: No such file or directory
sed: can't read proc_dep_list: No such file or directory
sed: can't read proc_dep_list: No such file or directory
sed: can't read proc_dep_list: No such file or directory
cat: proc_dep_list: No such file or directory
rm: cannot remove ‘proc_dep_list’: No such file or directory
rm: cannot remove ‘dep.txt’: No such file or directory
rm: cannot remove ‘dep1.txt’: No such file or directory
```

**Comment by StefanSalewski** [comment]
On Wed, 2016-01-20 at 04:38 -0800, ephja wrote:
> home/exe/src/nim-libs/nim-gtk3/gen/tmp_gtk/finalh(2712, 33) Error:
> ';' expected

What is your desire?

My generator script can be used only with c2nim96 and with gtk headers
3.15.xx

You do not need that script, you can use the included *.nim files, they
should work with gtk 3.16 and Nim 0.13. Maybe some minimal fixes are
necessary, you can do it with a text editor.

Fixing the generator scrips is some work, c2nim has changed a lot. I
told you in the forum, I can do that, but its makes only sense when
people really intend to use GTK3 with Nim. And from Forum discussion,
no one wants that. Estimated work is 150 h, for the ten wrappers. That
is not much because c2nim works much better now, it has bitfield
support and noforward pragma should work. (Initial release took me 500
hours last winter.)

You may know that we consider to add GC support, which is much easier
when delegates work.

**Comment by StefanSalewski** [comment]
Sorry, for my email reply I just got the long list of errors, but not your initial question.

Yes, it is due to c2nim, and maybe due to gtk 3.20?

**Comment by ephja** [comment]
Don't I need to run that script in order to get the gdk3 module?

**Comment by StefanSalewski** [comment]
On Wed, 2016-01-20 at 08:14 -0800, ephja wrote:
> Don't I need to run that script in order to get the gdk3 module?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/StefanSalewski/nim-gtk3/issues/4#issuecomment-1732
> 53949

All necessary wrapper modules are on github:

https://github.com/StefanSalewski?tab=repositories

I think 10 total. You have to download them all manually, sorry. And
you have to create links to these directories in your working
directory. Or copy just the *.nim files into your working directory.

Nimble install can not work unfortunately currently because of name
conflicts with the old legacy wrappers shipped with Nim.

Maybe, when people lost interest in GTK2 fully in a few years, GTK2
will not be shipped with Nim any more, then I may create a nimble
package. I hesitate to name them cairo-salewski.nim or so.

Please not that there are some minor bugs in the *.nim files, one
example is pango-cairo, which I just discovered yesterday. The name of
the library is not pango, but pangocairo. You can fix that with your
text editor in a few seconds -- I hesitate to touch my generator
scripts for these small bugs. There may be some more bugs of course, it
needs some testing, GTK and related libs are big, and I am currently
the only one using it, so fully testing may take long. And I can test
only for Linux myself.

**Comment by ephja** [comment]
So they'll become dependencies at some point then. Thanks.
